apiVersion: v1
kind: Pod
metadata:
  name: mlp_cnn
  labels:
    k8s-app: mlp_cnn
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-GTX-3090
  containers:
  - name: mypod
    image: ubuntu
    resources:
      limits:
        memory: "32000Mi"
        cpu: "16000m"
        nvidia.com/gpu: "1"
      requests:
        memory: "32000Mi"
        cpu: "16000m"
        nvidia.com/gpu: "1"
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: workingdirectory
      mountPath: /working
  volumes:
  - name: workingdirectory
    emptyDir: {}
